/**
 * Drizzle ORM schema for Project Vajra.
 *
 * Defines 13 tables, 6 PostgreSQL enums, and all relation mappings.
 * Tables are grouped into:
 *   - **Auth** — `user`, `session`, `account`, `verification` (managed by Better-Auth)
 *   - **Multi-tenant** — `gym_workspaces`, `branches`, `workspace_users`
 *   - **Business** — `plans`, `members`, `transactions`
 *   - **HRMS** — `employees`
 *   - **Platform** — `configuration`, `audit_logs`
 *
 * Every business table carries a `workspace_id` FK for application-level tenant isolation.
 *
 * @module lib/db/schema
 */
import { relations } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  boolean,
  timestamp,
  uuid,
  integer,
  varchar,
  jsonb,
  numeric,
} from "drizzle-orm/pg-core";

// ─── Auth Tables (Better-Auth) ──────────────────────────────────────────────
/** Auth user account. PK is a text ID generated by Better-Auth. */export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** Server-side auth session. One user can have many active sessions (multi-device). */
export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** Auth provider credential. Stores hashed password for email/password provider. */
export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** Email verification tokens (managed by Better-Auth). */
export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ─── Multi-Tenant Tables ────────────────────────────────────────────────────

/** Root tenant entity — represents a gym organisation. All business data hangs off this. */
export const gymWorkspaces = pgTable("gym_workspaces", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  primaryBranchName: text("primary_branch_name").notNull(),
  ownerUpiId: text("owner_upi_id"),
  upiQrImageUrl: text("upi_qr_image_url"),
  whatsappTemplate: text("whatsapp_template"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** Physical gym location within a workspace. Supports GPS coordinates for geofencing. */
export const branches = pgTable("branches", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  contactPhone: text("contact_phone"),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/** RBAC roles: SUPER_ADMIN (full), MANAGER (ops), RECEPTIONIST (front-desk), TRAINER (floor). */
export const workspaceRoleEnum = pgEnum("workspace_role", [
  "SUPER_ADMIN",
  "MANAGER",
  "RECEPTIONIST",
  "TRAINER",
]);

/** Junction table linking auth users to workspaces with a role. Supports optional branch assignment. */
export const workspaceUsers = pgTable("workspace_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: workspaceRoleEnum("role").notNull().default("RECEPTIONIST"),
  assignedBranchId: uuid("assigned_branch_id").references(() => branches.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ─── Plans, Members & Transactions ──────────────────────────────────────────

/** Subscription plan template. Price in INR (integer paise-free — stored as whole rupees). */
export const plans = pgTable("plans", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  price: integer("price").notNull(),
  durationDays: integer("duration_days").notNull(),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/** Member lifecycle: PENDING_PAYMENT → ACTIVE → EXPIRED. Cron re-checks daily. */
export const memberStatusEnum = pgEnum("member_status", [
  "ACTIVE",
  "EXPIRED",
  "PENDING_PAYMENT",
]);

/** Gym member (end customer). Scoped to workspace + branch. Has a 4-digit kiosk check-in PIN. */
export const members = pgTable("members", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  branchId: uuid("branch_id")
    .notNull()
    .references(() => branches.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  phone: varchar("phone", { length: 20 }).notNull(),
  email: varchar("email", { length: 255 }),
  checkinPin: varchar("checkin_pin", { length: 4 }),
  status: memberStatusEnum("status").notNull().default("PENDING_PAYMENT"),
  expiryDate: timestamp("expiry_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/** Supported payment methods for transactions. */
export const paymentMethodEnum = pgEnum("payment_method", ["UPI", "CASH"]);

/** Transaction lifecycle: PENDING (awaiting payment) → COMPLETED. */
export const transactionStatusEnum = pgEnum("transaction_status", [
  "COMPLETED",
  "PENDING",
]);

/** Payment record linking a member to their plan purchase. Amount in whole INR. */
export const transactions = pgTable("transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  memberId: uuid("member_id")
    .notNull()
    .references(() => members.id, { onDelete: "cascade" }),
  planId: uuid("plan_id")
    .notNull()
    .references(() => plans.id, { onDelete: "cascade" }),
  amount: integer("amount").notNull(),
  paymentMethod: paymentMethodEnum("payment_method").notNull().default("UPI"),
  status: transactionStatusEnum("status").notNull().default("PENDING"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ─── Employees & Attendance ─────────────────────────────────────────────────

/** Employee role (lowercase, distinct from workspace_role which is uppercase). */
export const employeeRoleEnum = pgEnum("employee_role", [
  "manager",
  "trainer",
  "receptionist",
]);

/** Employee onboarding status: invited → active → left. */
export const employeeStatusEnum = pgEnum("employee_status", [
  "active",
  "invited",
  "left",
]);

/** Staff member record. Optionally linked to an auth user via `userId`. */
export const employees = pgTable("employees", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  branchId: uuid("branch_id")
    .notNull()
    .references(() => branches.id, { onDelete: "cascade" }),
  userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 20 }),
  role: employeeRoleEnum("role").notNull().default("receptionist"),
  status: employeeStatusEnum("status").notNull().default("invited"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Employee invite tokens. Sent via email OTP.
 * The token is a 6-digit OTP code, hashed before storage.
 * Expires after 24 hours. One active invite per employee at a time.
 */
export const employeeInvites = pgTable("employee_invites", {
  id: uuid("id").primaryKey().defaultRandom(),
  employeeId: uuid("employee_id")
    .notNull()
    .references(() => employees.id, { onDelete: "cascade" }),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  email: varchar("email", { length: 255 }).notNull(),
  otpHash: text("otp_hash").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  consumed: boolean("consumed").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ─── Attendance ─────────────────────────────────────────────────────────────

/**
 * Member attendance log. Records check-in and check-out timestamps.
 * A row is created on kiosk check-in with `checkedOutAt` NULL.
 * The next PIN entry by the same member closes the open session (sets `checkedOutAt`).
 * If no checkout occurs, it's an open session (gym can auto-close via cron later).
 */
export const attendance = pgTable("attendance", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  branchId: uuid("branch_id")
    .notNull()
    .references(() => branches.id, { onDelete: "cascade" }),
  memberId: uuid("member_id")
    .notNull()
    .references(() => members.id, { onDelete: "cascade" }),
  checkedInAt: timestamp("checked_in_at").notNull().defaultNow(),
  checkedOutAt: timestamp("checked_out_at"),
});

// ─── Configuration ──────────────────────────────────────────────────────────

/** Per-branch configuration: checkout toggle, theme, default plan. Falls back to workspace-level. */
export const configuration = pgTable("configuration", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  branchId: uuid("branch_id").references(() => branches.id, {
    onDelete: "cascade",
  }),
  checkoutEnabled: boolean("checkout_enabled").notNull().default(false),
  themeMode: varchar("theme_mode", { length: 20 }).notNull().default("system"),
  defaultPlanId: uuid("default_plan_id").references(() => plans.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ─── Audit Logs ─────────────────────────────────────────────────────────────

/** Immutable audit trail. Records every significant action with JSONB details. Cleaned up after 6 months by cron. */
export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => gymWorkspaces.id, { onDelete: "cascade" }),
  userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
  action: varchar("action", { length: 100 }).notNull(),
  entityType: varchar("entity_type", { length: 50 }).notNull(),
  entityId: varchar("entity_id", { length: 255 }),
  details: jsonb("details"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ─── Relations ──────────────────────────────────────────────────────────────

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  workspaceUsers: many(workspaceUsers),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const gymWorkspaceRelations = relations(gymWorkspaces, ({ many }) => ({
  branches: many(branches),
  workspaceUsers: many(workspaceUsers),
  plans: many(plans),
  members: many(members),
  transactions: many(transactions),
  auditLogs: many(auditLogs),
  configurations: many(configuration),
  employees: many(employees),
}));

export const branchRelations = relations(branches, ({ one, many }) => ({
  workspace: one(gymWorkspaces, {
    fields: [branches.workspaceId],
    references: [gymWorkspaces.id],
  }),
  assignedUsers: many(workspaceUsers),
  members: many(members),
  employees: many(employees),
}));

export const workspaceUserRelations = relations(workspaceUsers, ({ one }) => ({
  workspace: one(gymWorkspaces, {
    fields: [workspaceUsers.workspaceId],
    references: [gymWorkspaces.id],
  }),
  user: one(user, {
    fields: [workspaceUsers.userId],
    references: [user.id],
  }),
  assignedBranch: one(branches, {
    fields: [workspaceUsers.assignedBranchId],
    references: [branches.id],
  }),
}));

export const planRelations = relations(plans, ({ one, many }) => ({
  workspace: one(gymWorkspaces, {
    fields: [plans.workspaceId],
    references: [gymWorkspaces.id],
  }),
  transactions: many(transactions),
}));

export const memberRelations = relations(members, ({ one, many }) => ({
  workspace: one(gymWorkspaces, {
    fields: [members.workspaceId],
    references: [gymWorkspaces.id],
  }),
  branch: one(branches, {
    fields: [members.branchId],
    references: [branches.id],
  }),
  transactions: many(transactions),
  attendanceLogs: many(attendance),
}));

export const transactionRelations = relations(transactions, ({ one }) => ({
  workspace: one(gymWorkspaces, {
    fields: [transactions.workspaceId],
    references: [gymWorkspaces.id],
  }),
  member: one(members, {
    fields: [transactions.memberId],
    references: [members.id],
  }),
  plan: one(plans, {
    fields: [transactions.planId],
    references: [plans.id],
  }),
}));

export const auditLogRelations = relations(auditLogs, ({ one }) => ({
  workspace: one(gymWorkspaces, {
    fields: [auditLogs.workspaceId],
    references: [gymWorkspaces.id],
  }),
  user: one(user, {
    fields: [auditLogs.userId],
    references: [user.id],
  }),
}));

export const configurationRelations = relations(configuration, ({ one }) => ({
  workspace: one(gymWorkspaces, {
    fields: [configuration.workspaceId],
    references: [gymWorkspaces.id],
  }),
  branch: one(branches, {
    fields: [configuration.branchId],
    references: [branches.id],
  }),
  defaultPlan: one(plans, {
    fields: [configuration.defaultPlanId],
    references: [plans.id],
  }),
}));

export const employeeRelations = relations(employees, ({ one, many }) => ({
  workspace: one(gymWorkspaces, {
    fields: [employees.workspaceId],
    references: [gymWorkspaces.id],
  }),
  branch: one(branches, {
    fields: [employees.branchId],
    references: [branches.id],
  }),
  user: one(user, {
    fields: [employees.userId],
    references: [user.id],
  }),
  invites: many(employeeInvites),
}));

export const employeeInviteRelations = relations(employeeInvites, ({ one }) => ({
  employee: one(employees, {
    fields: [employeeInvites.employeeId],
    references: [employees.id],
  }),
  workspace: one(gymWorkspaces, {
    fields: [employeeInvites.workspaceId],
    references: [gymWorkspaces.id],
  }),
}));

export const attendanceRelations = relations(attendance, ({ one }) => ({
  workspace: one(gymWorkspaces, {
    fields: [attendance.workspaceId],
    references: [gymWorkspaces.id],
  }),
  branch: one(branches, {
    fields: [attendance.branchId],
    references: [branches.id],
  }),
  member: one(members, {
    fields: [attendance.memberId],
    references: [members.id],
  }),
}));


